/*
 * This file is generated by jOOQ.
 */
package com.ynz.demo.jooqdao.model;


import com.ynz.demo.jooqdao.model.tables.Book;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
